[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "https://zen-booth-7b30d6.netlify.com/*"
  to = "https://www.ionvarsescu.tk/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "https://affectionate-yalow-1e0141.netlify.com/*"
  to = "https://www.ionvarsescu.tk/portofolio/:splat"
  status = 200
  force = false